apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: valhalla

bases:
- ../../base

commonLabels:
  environment: dev

# Using official Valhalla image
# No custom image build needed

replicas:
- name: valhalla-api
  count: 2

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
